#Servers:
#  BC_MONGODB: 192.168.4.158
#  PORT_MONGODB: 27017

Urls:
  Base_Url: "http://test.mybesttoken.com"
  Time_Out: 5
  Get_Token_All: "/api/v3/token/all"
  Symbol_Flow: "/api/v3/fundflow/binance/btc-usdt/1d?last=1"
  Message: "/api/v1/message/news/Bitcoin?lang=cn&time=&limit="
  Telegram: "/api/v1/message/telegram/Bitcoin?lang=cn&time=&limit="
  Twitter: "/api/v1/message/twitter/Bitcoin?lang=cn&time=&limit="
  Token_Grade: "/api/v3/grade"
  Version: "/api/v3/version"
  Login: "/api/v3/signin"
  Logout: "/api/v3/signout"


#email:
#  smtp_addr: "smtp.laplacetech.cn"
#  from_addr: "liangfenglong@laplacetech.cn"
#  emai_pwd: "Admin@123"
#  to_addr: "liangfenglong@laplacetech.cn"

Login:
  Mobile: "18600000000"
  Valid: "999888"
