Urls:
  Base_Url: "http://test.mybesttoken.com"
  Time_Out: 5
  Get_Token_All: "/api/v3/token/all"
  Symbol_Flow: "/api/v3/fundflow/binance/btc-usdt/1d?last=1"
  Message: "/api/v1/message/news/Bitcoin?lang=cn&time=&limit="
  Telegram: "/api/v1/message/telegram/Bitcoin?lang=cn&time=&limit="
  Twitter: "/api/v1/message/twitter/Bitcoin?lang=cn&time=&limit="
  Token_Grade: "/api/v3/grade"
  Version: "/api/v3/version"
  Login: "/api/v3/signin"
  Logout: "/api/v3/signout"


Login:
  Mobile: "18600000000"
  Valid: "999888"
