Servers:
  BC_MONGODB: "192.168.4.158"
  PORT_MONGODB: 27017

Urls:
  Base_Url: "http://test.mybesttoken.com"
  Time_Out: 5
  Get_Token_All: "/api/v3/token/all"
  Symbol_Flow: "/api/v3/fundflow/{}/{}/{}?{}"
  Message: "/api/v1/message/news/{}?lang={}&time={}&limit={}"
  Telegram: "/api/v1/message/telegram/{}?lang={}&time={}&limit={}"
  Twitter: "/api/v1/message/twitter/{}?lang={}&time={}&limit={}"
  Token_Grade: "/api/v3/grade"
  Version: "/api/v3/version"
  Login: "/api/v3/signin"
  Logout: "/api/v3/signout"
  token_index: "/api/v3/token/index"
  token_code: "/api/v3/token/{}"
  token_quotation_ranking_change_ratio_24h: "/api/v3/quotation/ranking/change_ratio_24h"
  token_candle: "/api/v3/candle/{}/{}"
  message_news: "/api/v1/message/news/{}"
  f10_intro: "/api/v1/f10/intro/{}"
  f10_links: "/api/v1/f10/links/{}"
  symbol_list: "/api/v3/symbol"
  symbol_index: "/api/v3/symbol/index"
  symbol_pricediff: "/api/v2/symbol/pricediff"
  symbol_detail: "/api/v3/symbol/{}/{}"
  symbol_rank: "/api/v3/symbol/ranking"
  symbol_rank_abbr: "/api/v3/symbol/ranking?abbr={}"
  symbol_rank_volume: "/api/v3/symbol/ranking?field=volume"
  markets: "/api/v3/markets"
  candle: "/api/v3/candle/{}/{}/{}"
  tokens_flow: "/api/v2/tokens/flow/{}"
  homepage_sort: "/api/v3/home/rank_index"
  news: "/api/v1/message"
  refreshtoken: "/api/v3/refreshtoken"
  star_tokens: "/api/v3/my/star/tokens"



Login:
  Mobile: "18600000000"
  Valid: "999888"
